In [1]:
# 넘파이 모듈 import 

import numpy as np

#### 넘파이 배열 생성
##### 1) 파이썬 자료 구조 이용

In [17]:
arr1 = np.array([0,2,4])
arr1

array([0, 2, 4])

In [18]:
arr2 = np.array([[1,2,3],[2,3,4]])
arr2

array([[1, 2, 3],
       [2, 3, 4]])

In [10]:
# arr1과 arr2 의 타입 확인

print(f"type : {type(arr1)}")
print(f"type : {type(arr2)}")

type : <class 'numpy.ndarray'>
type : <class 'numpy.ndarray'>


In [13]:
# int와 object 타입이 섞일 때 object로 변환됨

arr3 = np.array(['1','2','3',4])
print(arr3, arr3.dtype)

['1' '2' '3' '4'] <U21


In [14]:
# int, float가 섞일때 float 로 변환됨
arr3 = np.array([1,2.0,3.0,4,])
print(arr3, arr3.dtype)

[1. 2. 3. 4.] float64


##### 2) 넘파이 배열 생성 함수

In [19]:
# zeros() :0을 5개 가지는 ndarray 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
# 0으로 채워지는 4행 5열 ndarray
arr = np.zeros(shape=(4,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [2]:
# ones() : 1을 5개 가지는 ndarray 생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [3]:
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.empty(4)

array([1., 2., 3., 4.])

In [30]:
# 2행 2열, float 타입, 임의의 값
arr1 = np.empty(shape=(2,2))

# 2행 2열, int 타입, 임의의 값
arr2 = np.empty(shape=(2,2), dtype=int)

print(arr1)
print(arr2)


[[1. 2.]
 [3. 4.]]
[[4607182418800017408 4611686018427387904]
 [4613937818241073152 4616189618054758400]]


In [25]:
# eye() : 대각선에는 값1, 그 밖의 위치에 값 0을 가지는 nxn 배열 생성
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
# k : 대각선을 기준으로 지정한 값만큼 1단계 위로 1이 배치된다
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [26]:
# linspace() : 시작값과 종료값을 이용해 균등하게 분할된 배열 생성
np.linspace(start=2.0, stop=3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [34]:
np.linspace(start=2.0, stop=3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

##### arrange()
> arange([start,] stop[, step,], dtype=None, *, device=None, like=None)
>
> 배열 생성 시 종료값은 포함하지 않음


In [37]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [38]:
np.arange(5,9)

array([5, 6, 7, 8])

In [39]:
np.arange(10,20, step=2)

array([10, 12, 14, 16, 18])

#### 차원 및 크기 변경
##### reshape(행, 열)

In [40]:
np.arange(10,20).reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
# 다차원 배열을 1차원으로 변경
arr1 = np.arange(12).reshape(3,4)
arr1.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
# 행은 4로 고정, 열 크기는 자동
np.arange(12).reshape(4,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [52]:
# 3차원 배열 생성
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([0, 1, 2, 3, 4])