In [1]:
# 넘파이 모듈 import 

import numpy as np

In [3]:
arr = np.array([[1,2,3],[4,5,6]], dtype='int32')
print(arr)

[[1 2 3]
 [4 5 6]]


In [4]:
# 열 방향 연산
arr.sum(axis=0)

array([5, 7, 9])

In [5]:
# 행 방향 연산
arr.sum(axis=1)

array([ 6, 15])

#### 3차원 배열 연산

In [11]:
arr = np.arange(36).reshape(3,4,3)
print(arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [12]:
# 두번째 대괄호 기준
arr.sum(axis=0)

array([[36, 39, 42],
       [45, 48, 51],
       [54, 57, 60],
       [63, 66, 69]])

In [13]:
# 가장 안쪽 대괄호 기준
arr.sum(axis=1)

array([[ 18,  22,  26],
       [ 66,  70,  74],
       [114, 118, 122]])

In [14]:
arr.sum(axis=2)

array([[  3,  12,  21,  30],
       [ 39,  48,  57,  66],
       [ 75,  84,  93, 102]])

### 임의의 수 


In [15]:
np.random.rand(3,2)

array([[0.06760175, 0.197133  ],
       [0.32824957, 0.6406253 ],
       [0.36768341, 0.89987085]])

In [16]:
# 임의의 정수반환
np.random.randint(5, size=(2,4))

array([[3, 0, 0, 1],
       [4, 2, 2, 4]], dtype=int32)

In [19]:
# 1차원 배열에서 임의의 샘플 생성
# 10 : 0~9
np.random.choice(10, 3)

array([1, 0, 3], dtype=int32)

In [20]:
# 5개 숫자 중 확률 지정(1,4의 확률은 0)
np.random.choice(5, 3, p=[0.1,0,0.3,0.6,0])

array([3, 0, 3], dtype=int32)

In [23]:
aa_milne_arr = ['pooh', 'rabbit', 'piglet', 'Christopher']
np.random.choice(aa_milne_arr, 5, p=[0.5, 0.1, 0.1, 0.3])

array(['pooh', 'pooh', 'piglet', 'pooh', 'Christopher'], dtype='<U11')

In [21]:
# replace() : 중복되는 요소 추출 여부
np.random.choice(np.arange(12), size=10, replace=True)

array([ 0, 11,  2,  9,  0, 10,  7,  8,  4,  6])

In [22]:
np.random.choice(np.arange(12), size=10, replace=False)

array([ 1,  5,  6, 11,  8,  7, 10,  4,  2,  0])

#### 행렬 내적

In [28]:
a = [1, 2, 3]
b = [4, 5, 6]
print(np.dot(a,b))

32


In [26]:
# 2차원 배열 내적
a = [[1, 2, 3], [4, 5, 6]]
b = [[7, 8], [9, 10], [11, 12]]
np.dot(a, b)

array([[ 58,  64],
       [139, 154]])

#### 전치행렬

In [31]:
a = np.array([[1,2],[3,4]])

transpose_matrix = np.transpose(a)
print(f"a 의 원본 \n {a}")
print(f"a 의 전치행렬 \n {transpose_matrix}")

a 의 원본 
 [[1 2]
 [3 4]]
a 의 전치행렬 
 [[1 3]
 [2 4]]
