In [1]:
# 넘파이 모듈 import 

import numpy as np

In [5]:
# 0~9 까지의 ndarray 생성
arr1 = np.arange(10)

# 인덱싱이 3번인 데이터 추출
# 인덱싱 0 부터 시작
print(arr1[3])

3


In [7]:
# 0~9 까지의 ndarray 생성
arr1 = np.arange(10).reshape(2,5)
print(arr1)

# 7 가져오기
print(arr1[1,2])

[[0 1 2 3 4]
 [5 6 7 8 9]]
7


In [9]:
arr3d = np.arange(24).reshape(2,3,4)
# 18 조회
print(arr3d[1,1,2])

18


> #### 슬라이싱

In [10]:
arr1d = np.arange(start=1, stop=10)
print(arr1d[:3])  # 0 ~ 2 인덱스 조회
print(arr1d[5:])  # 5번 인덱스 부터 끝까지 조회
print(arr1d[:])   # 전체 조회

[1 2 3]
[6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [20]:
# 2차원 배열에서의 다양한 슬라이싱

arr2d = arr1d.reshape(3,3)
print(f"{arr2d}\n")

print(f"arr2d[0:2, 0:2] \n {arr2d[0:2, 0:2]}\n")
print(f"arr2d[1:3, 0:3] \n {arr2d[1:3, 0:3]}\n")
print(f"arr2d[1:3, :] \n {arr2d[1:3, :]}\n")
print(f"arr2d[:, :] \n {arr2d[:, :]}\n")
print(f"arr2d[:2, 1:] \n {arr2d[:2, 1:]}\n")
print(f"arr2d[:2, 0] \n {arr2d[:2, 0]}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

arr2d[0:2, 0:2] 
 [[1 2]
 [4 5]]

arr2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]

arr2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]

arr2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

arr2d[:2, 1:] 
 [[2 3]
 [5 6]]

arr2d[:2, 0] 
 [1 4]


> #### 팬시 인덱싱

In [25]:
arr1d = np.arange(start=1, stop=10)
arr2d = arr1d.reshape(3,3)

# (0,2),(1,2) 를 의미
arr3 = arr2d[[0,1], 2]
print(f"arr2d[[0,1], 2] : {arr3.tolist()}\n")

# (0,0),(0,1)
# (1,0),(1,1)
arr4 = arr2d[[0,1], 0:2]
print(f"arr2d[[0,1], 0:2] : {arr4.tolist()}\n")

# (0,0),(0,1), (0,2)
# (1,0),(1,1), (1,2)
arr5 = arr2d[[0,1]]
print(f"arr2d[[0,1]] : {arr5.tolist()}\n")

arr2d[[0,1], 2] : [3, 6]

arr2d[[0,1], 0:2] : [[1, 2], [4, 5]]

arr2d[[0,1]] : [[1, 2, 3], [4, 5, 6]]



#### 불린 인덱싱

In [26]:
arr2d = np.arange(12).reshape(3,4)
print(arr2d)

# 5보다 큰 요소 반환
arr2d[arr2d > 5]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6,  7,  8,  9, 10, 11])

In [27]:
# 2차원 불리언 배열로 3차원 배열 인덱싱

arr3d = np.arange(24).reshape(2,3,4)
print(arr3d)

condition = [[True, False, True], [False, True, False]]

arr3d[condition]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])