In [1]:
# 넘파이 모듈 import 

import numpy as np

In [16]:
origin_arr = np.array([3,1,9,5,2])
print(f"원본 : {origin_arr}")
# np.sort() : 원 배열은 그대로, 변환하여 반환
sorted = np.sort(origin_arr)
print(f"sort() 호출 후 원본 : {origin_arr}")
print(f"정렬본 : {sorted}")

원본 : [3 1 9 5 2]
sort() 호출 후 원본 : [3 1 9 5 2]
정렬본 : [1 2 3 5 9]


In [18]:
origin_arr = np.array([3,1,9,5,2])
print(f"원본 : {origin_arr}")
# ndarray.sort() : 원 배열을 변환하여 반환
sorted = origin_arr.sort()
print(f"sort() 호출 후 원본 : {origin_arr}")
print(f"정렬본 : {sorted}")

원본 : [3 1 9 5 2]
sort() 호출 후 원본 : [1 2 3 5 9]
정렬본 : None


In [19]:
# 내림차순

origin_arr = np.array([3,1,9,5,2])
sorted = np.sort(origin_arr)[::-1]
print(f"정렬본 : {sorted}")

정렬본 : [9 5 3 2 1]


In [31]:
arr = np.array([[1,4],[3,1]])
print(f"원본\n {arr}\n")

# 축을 지정하지 않으면 -1 : 마지막 축 기준
print(f"마지막 축 기준 \n {np.sort(arr)}\n")  

# None : 배열을 해제 후 [1,4,3,1] 후 sort 함
print(f"배열 해제 후 sort \n {np.sort(arr, axis=None)}\n")  

print(f"행 기준 sort \n {np.sort(arr, axis=0)}\n")
print(f"열 기준 sort \n {np.sort(arr, axis=1)}\n")

원본
 [[1 4]
 [3 1]]

마지막 축 기준 
 [[1 4]
 [1 3]]

배열 해제 후 sort 
 [1 1 3 4]

행 기준 sort 
 [[1 1]
 [3 4]]

열 기준 sort 
 [[1 4]
 [1 3]]



In [33]:
origin_arr = np.array([3,1,9,5,2])
print(f"원본 : {origin_arr}")
origin_idx = np.argsort(origin_arr)
print(f"sort() 호출 후 원본 : {origin_arr}")
print(f"정렬 전 인덱스 : {origin_idx}")

원본 : [3 1 9 5 2]
sort() 호출 후 원본 : [3 1 9 5 2]
정렬 전 인덱스 : [1 4 0 3 2]


In [36]:
# 시험 성적 순으로 학생 이름 출력

name_arr = np.array(["John","Mike","Sarah","Kate","Samuel"])
score_arr = np.array([76,93,82,97,86])

idx_asc = np.argsort(score_arr)
print(f"성적 오름차순 정렬 후 이름 출력 {name_arr[idx_asc]}")

idx_desc = np.argsort(score_arr)[::-1]
print(f"성적 내림차순 정렬 후 이름 출력 {name_arr[idx_desc]}")

성적 오름차순 정렬 후 이름 출력 ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
성적 내림차순 정렬 후 이름 출력 ['Kate' 'Mike' 'Samuel' 'Sarah' 'John']
