In [22]:
import numpy as np

In [23]:
# Quiz1) 다음 리스트를 이용해 ndarray를 생성하시오.

list1 = [100,75,95,36,85,45,55,78,43,59]
arr1 = np.array(list1)
arr1

array([100,  75,  95,  36,  85,  45,  55,  78,  43,  59])

In [24]:
# Quiz2) 70~100 사이의 수를 이용해 ndarray를 생성하시오.
# 종료 값은 포함하고, 9개의 숫자를 int 타입으로 생성하시오

arr2 = np.linspace(70, 100, 9, dtype=int)
arr2

array([ 70,  73,  77,  81,  85,  88,  92,  96, 100])

In [25]:
# # Quiz3) 0~30까지의 수를 이용해 3차원 배열을 생성하시오. (2면 5행 3열)
arr3 = np.arange(30).reshape(2,5,3)
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [33]:
# Quiz4) Quiz2번에서 생성한 배열을 2차원 형태로 변경하시오(3행 3열)

# arr2.reshape(3,-1)
arr2_reshape = arr2.reshape(3,3)
arr2_reshape

array([[ 70,  73,  77],
       [ 81,  85,  88],
       [ 92,  96, 100]])

In [27]:
# Quiz5) Quiz1번에서 생성한 배열을 오름차순 및 내림차순으로 정렬하시오.(원본은 변경하지 않음)

# 오름차순
print(np.sort(arr1))

# 내림차순
print(np.sort(arr1)[::-1])

[ 36  43  45  55  59  75  78  85  95 100]
[100  95  85  78  75  59  55  45  43  36]


In [34]:
# Quiz6) Quiz4번에서 변경한 2차원 배열을 행기준으로 내림차순 정렬하시오

np.sort(arr2_reshape, axis=0)[::-1]

array([[ 92,  96, 100],
       [ 81,  85,  88],
       [ 70,  73,  77]])

In [16]:
# Quiz7) Quiz1번에서 생성한 배열에서 60 점 이상의 배열을 추출하시오.

arr1[arr1 >= 60]

array([100,  75,  95,  85,  78])

In [36]:
# Quiz8) Quiz1에서 생성한 배열의 합을 구하시외

print(np.sum(arr1))

671
